require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - Gemfile
    - vendor/**/*
    - config/environments/*
    - bin/**/*
    - lib/**/*.rake
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - app/**/application_*.rb
    - Rakefile
    - config.ru
    - config/**/*

# METRICS
Metrics/MethodLength:
  Max: 300



Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 90

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

# STYLE
Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Proc:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  
Style/StringLiterals:
  Enabled: false
  
Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/FilePath:
  Enabled: false
  
Rails/HasManyOrHasOneDependent:
  Enabled: false
