# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - api-balance-control-db
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=api-balance-control-db
      - DATABASE_PORT=5432
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
  api-balance-control-db:
    image: postgres:alpine3.16
    container_name: api-balance-control-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ${HOME}/docker/postgresql/api-balance-control-db:/var/lib/postgresql:z
    ports:
      - "55433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
  gem_cache:
