default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') {5} %>
  timeout: 5000

development:
  <<: *default
  database: balance-control-dev

test:
  <<: *default
  database: balance-control-test

production:
  <<: *default
  database: balance-control-production